services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - api
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    environment:
      PORT: 3000
      DB_PATH: /data/pax_imperia.db
    volumes:
      - api-data:/data
    restart: unless-stopped

volumes:
  api-data:
